//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CILantro.Engine.Parser {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GrammarNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GrammarNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CILantro.Engine.Parser.GrammarNames", typeof(GrammarNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddovfToken.
        /// </summary>
        internal static string AddovfToken {
            get {
                return ResourceManager.GetString("AddovfToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddovfunToken.
        /// </summary>
        internal static string AddovfunToken {
            get {
                return ResourceManager.GetString("AddovfunToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddToken.
        /// </summary>
        internal static string AddToken {
            get {
                return ResourceManager.GetString("AddToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlgorithmToken.
        /// </summary>
        internal static string AlgorithmToken {
            get {
                return ResourceManager.GetString("AlgorithmToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlignmentToken.
        /// </summary>
        internal static string AlignmentToken {
            get {
                return ResourceManager.GetString("AlignmentToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AndToken.
        /// </summary>
        internal static string AndToken {
            get {
                return ResourceManager.GetString("AndToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnsiToken.
        /// </summary>
        internal static string AnsiToken {
            get {
                return ResourceManager.GetString("AnsiToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssemblyAttributes.
        /// </summary>
        internal static string AssemblyAttributes {
            get {
                return ResourceManager.GetString("AssemblyAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssemblyDeclaration.
        /// </summary>
        internal static string AssemblyDeclaration {
            get {
                return ResourceManager.GetString("AssemblyDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssemblyDeclarations.
        /// </summary>
        internal static string AssemblyDeclarations {
            get {
                return ResourceManager.GetString("AssemblyDeclarations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssemblyHead.
        /// </summary>
        internal static string AssemblyHead {
            get {
                return ResourceManager.GetString("AssemblyHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssemblyOrRefDeclaration.
        /// </summary>
        internal static string AssemblyOrRefDeclaration {
            get {
                return ResourceManager.GetString("AssemblyOrRefDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssemblyRefDeclaration.
        /// </summary>
        internal static string AssemblyRefDeclaration {
            get {
                return ResourceManager.GetString("AssemblyRefDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssemblyRefDeclarations.
        /// </summary>
        internal static string AssemblyRefDeclarations {
            get {
                return ResourceManager.GetString("AssemblyRefDeclarations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssemblyRefHead.
        /// </summary>
        internal static string AssemblyRefHead {
            get {
                return ResourceManager.GetString("AssemblyRefHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoToken.
        /// </summary>
        internal static string AutoToken {
            get {
                return ResourceManager.GetString("AutoToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeforefieldinitToken.
        /// </summary>
        internal static string BeforefieldinitToken {
            get {
                return ResourceManager.GetString("BeforefieldinitToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeqsToken.
        /// </summary>
        internal static string BeqsToken {
            get {
                return ResourceManager.GetString("BeqsToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeqToken.
        /// </summary>
        internal static string BeqToken {
            get {
                return ResourceManager.GetString("BeqToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BgesToken.
        /// </summary>
        internal static string BgesToken {
            get {
                return ResourceManager.GetString("BgesToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BgeToken.
        /// </summary>
        internal static string BgeToken {
            get {
                return ResourceManager.GetString("BgeToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BgeunsToken.
        /// </summary>
        internal static string BgeunsToken {
            get {
                return ResourceManager.GetString("BgeunsToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BgeunToken.
        /// </summary>
        internal static string BgeunToken {
            get {
                return ResourceManager.GetString("BgeunToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BgtsToken.
        /// </summary>
        internal static string BgtsToken {
            get {
                return ResourceManager.GetString("BgtsToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BgtToken.
        /// </summary>
        internal static string BgtToken {
            get {
                return ResourceManager.GetString("BgtToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BgtunsToken.
        /// </summary>
        internal static string BgtunsToken {
            get {
                return ResourceManager.GetString("BgtunsToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BgtunToken.
        /// </summary>
        internal static string BgtunToken {
            get {
                return ResourceManager.GetString("BgtunToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlesToken.
        /// </summary>
        internal static string BlesToken {
            get {
                return ResourceManager.GetString("BlesToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BleToken.
        /// </summary>
        internal static string BleToken {
            get {
                return ResourceManager.GetString("BleToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BleunsToken.
        /// </summary>
        internal static string BleunsToken {
            get {
                return ResourceManager.GetString("BleunsToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BleunToken.
        /// </summary>
        internal static string BleunToken {
            get {
                return ResourceManager.GetString("BleunToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BltsToken.
        /// </summary>
        internal static string BltsToken {
            get {
                return ResourceManager.GetString("BltsToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BltToken.
        /// </summary>
        internal static string BltToken {
            get {
                return ResourceManager.GetString("BltToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BltunsToken.
        /// </summary>
        internal static string BltunsToken {
            get {
                return ResourceManager.GetString("BltunsToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BltunToken.
        /// </summary>
        internal static string BltunToken {
            get {
                return ResourceManager.GetString("BltunToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BneunsToken.
        /// </summary>
        internal static string BneunsToken {
            get {
                return ResourceManager.GetString("BneunsToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BneunToken.
        /// </summary>
        internal static string BneunToken {
            get {
                return ResourceManager.GetString("BneunToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoolToken.
        /// </summary>
        internal static string BoolToken {
            get {
                return ResourceManager.GetString("BoolToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BrfalsesToken.
        /// </summary>
        internal static string BrfalsesToken {
            get {
                return ResourceManager.GetString("BrfalsesToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BrfalseToken.
        /// </summary>
        internal static string BrfalseToken {
            get {
                return ResourceManager.GetString("BrfalseToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BrsToken.
        /// </summary>
        internal static string BrsToken {
            get {
                return ResourceManager.GetString("BrsToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BrToken.
        /// </summary>
        internal static string BrToken {
            get {
                return ResourceManager.GetString("BrToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BrtruesToken.
        /// </summary>
        internal static string BrtruesToken {
            get {
                return ResourceManager.GetString("BrtruesToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BrtrueToken.
        /// </summary>
        internal static string BrtrueToken {
            get {
                return ResourceManager.GetString("BrtrueToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes.
        /// </summary>
        internal static string Bytes {
            get {
                return ResourceManager.GetString("Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CallConventions.
        /// </summary>
        internal static string CallConventions {
            get {
                return ResourceManager.GetString("CallConventions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CallKind.
        /// </summary>
        internal static string CallKind {
            get {
                return ResourceManager.GetString("CallKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CallToken.
        /// </summary>
        internal static string CallToken {
            get {
                return ResourceManager.GetString("CallToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CallvirtToken.
        /// </summary>
        internal static string CallvirtToken {
            get {
                return ResourceManager.GetString("CallvirtToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CeqToken.
        /// </summary>
        internal static string CeqToken {
            get {
                return ResourceManager.GetString("CeqToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CgtToken.
        /// </summary>
        internal static string CgtToken {
            get {
                return ResourceManager.GetString("CgtToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CgtunToken.
        /// </summary>
        internal static string CgtunToken {
            get {
                return ResourceManager.GetString("CgtunToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CharToken.
        /// </summary>
        internal static string CharToken {
            get {
                return ResourceManager.GetString("CharToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CilToken.
        /// </summary>
        internal static string CilToken {
            get {
                return ResourceManager.GetString("CilToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClassAttributes.
        /// </summary>
        internal static string ClassAttributes {
            get {
                return ResourceManager.GetString("ClassAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClassDeclaration.
        /// </summary>
        internal static string ClassDeclaration {
            get {
                return ResourceManager.GetString("ClassDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClassDeclarations.
        /// </summary>
        internal static string ClassDeclarations {
            get {
                return ResourceManager.GetString("ClassDeclarations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClassHead.
        /// </summary>
        internal static string ClassHead {
            get {
                return ResourceManager.GetString("ClassHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClassName.
        /// </summary>
        internal static string ClassName {
            get {
                return ResourceManager.GetString("ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClassToken.
        /// </summary>
        internal static string ClassToken {
            get {
                return ResourceManager.GetString("ClassToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CltToken.
        /// </summary>
        internal static string CltToken {
            get {
                return ResourceManager.GetString("CltToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CltunToken.
        /// </summary>
        internal static string CltunToken {
            get {
                return ResourceManager.GetString("CltunToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colon.
        /// </summary>
        internal static string Colon {
            get {
                return ResourceManager.GetString("Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma.
        /// </summary>
        internal static string Comma {
            get {
                return ResourceManager.GetString("Comma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComplexQuotedString.
        /// </summary>
        internal static string ComplexQuotedString {
            get {
                return ResourceManager.GetString("ComplexQuotedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CtorToken.
        /// </summary>
        internal static string CtorToken {
            get {
                return ResourceManager.GetString("CtorToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomAttributeDeclaration.
        /// </summary>
        internal static string CustomAttributeDeclaration {
            get {
                return ResourceManager.GetString("CustomAttributeDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomHead.
        /// </summary>
        internal static string CustomHead {
            get {
                return ResourceManager.GetString("CustomHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomType.
        /// </summary>
        internal static string CustomType {
            get {
                return ResourceManager.GetString("CustomType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DecInteger.
        /// </summary>
        internal static string DecInteger {
            get {
                return ResourceManager.GetString("DecInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declaration.
        /// </summary>
        internal static string Declaration {
            get {
                return ResourceManager.GetString("Declaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declarations.
        /// </summary>
        internal static string Declarations {
            get {
                return ResourceManager.GetString("Declarations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DivToken.
        /// </summary>
        internal static string DivToken {
            get {
                return ResourceManager.GetString("DivToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DivunToken.
        /// </summary>
        internal static string DivunToken {
            get {
                return ResourceManager.GetString("DivunToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dot.
        /// </summary>
        internal static string Dot {
            get {
                return ResourceManager.GetString("Dot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DotAssemblyToken.
        /// </summary>
        internal static string DotAssemblyToken {
            get {
                return ResourceManager.GetString("DotAssemblyToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DotClassToken.
        /// </summary>
        internal static string DotClassToken {
            get {
                return ResourceManager.GetString("DotClassToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DotCorflagsToken.
        /// </summary>
        internal static string DotCorflagsToken {
            get {
                return ResourceManager.GetString("DotCorflagsToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DotCtorToken.
        /// </summary>
        internal static string DotCtorToken {
            get {
                return ResourceManager.GetString("DotCtorToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DotCustomToken.
        /// </summary>
        internal static string DotCustomToken {
            get {
                return ResourceManager.GetString("DotCustomToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DotEntrypointToken.
        /// </summary>
        internal static string DotEntrypointToken {
            get {
                return ResourceManager.GetString("DotEntrypointToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DotFileToken.
        /// </summary>
        internal static string DotFileToken {
            get {
                return ResourceManager.GetString("DotFileToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DotHashToken.
        /// </summary>
        internal static string DotHashToken {
            get {
                return ResourceManager.GetString("DotHashToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DotImagebaseToken.
        /// </summary>
        internal static string DotImagebaseToken {
            get {
                return ResourceManager.GetString("DotImagebaseToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DotLocalsToken.
        /// </summary>
        internal static string DotLocalsToken {
            get {
                return ResourceManager.GetString("DotLocalsToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DotMaxstackToken.
        /// </summary>
        internal static string DotMaxstackToken {
            get {
                return ResourceManager.GetString("DotMaxstackToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DotMethodToken.
        /// </summary>
        internal static string DotMethodToken {
            get {
                return ResourceManager.GetString("DotMethodToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DotModuleToken.
        /// </summary>
        internal static string DotModuleToken {
            get {
                return ResourceManager.GetString("DotModuleToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DotPublickeytokenToken.
        /// </summary>
        internal static string DotPublickeytokenToken {
            get {
                return ResourceManager.GetString("DotPublickeytokenToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DotStackreserveToken.
        /// </summary>
        internal static string DotStackreserveToken {
            get {
                return ResourceManager.GetString("DotStackreserveToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DotSubsystemToken.
        /// </summary>
        internal static string DotSubsystemToken {
            get {
                return ResourceManager.GetString("DotSubsystemToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DotVerToken.
        /// </summary>
        internal static string DotVerToken {
            get {
                return ResourceManager.GetString("DotVerToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DupToken.
        /// </summary>
        internal static string DupToken {
            get {
                return ResourceManager.GetString("DupToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EqualsSign.
        /// </summary>
        internal static string EqualsSign {
            get {
                return ResourceManager.GetString("EqualsSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExtendsClause.
        /// </summary>
        internal static string ExtendsClause {
            get {
                return ResourceManager.GetString("ExtendsClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExtendsToken.
        /// </summary>
        internal static string ExtendsToken {
            get {
                return ResourceManager.GetString("ExtendsToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExternToken.
        /// </summary>
        internal static string ExternToken {
            get {
                return ResourceManager.GetString("ExternToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Float32Token.
        /// </summary>
        internal static string Float32Token {
            get {
                return ResourceManager.GetString("Float32Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Float64Token.
        /// </summary>
        internal static string Float64Token {
            get {
                return ResourceManager.GetString("Float64Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HexByte.
        /// </summary>
        internal static string HexByte {
            get {
                return ResourceManager.GetString("HexByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HexBytes.
        /// </summary>
        internal static string HexBytes {
            get {
                return ResourceManager.GetString("HexBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HexInteger.
        /// </summary>
        internal static string HexInteger {
            get {
                return ResourceManager.GetString("HexInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HidebysigToken.
        /// </summary>
        internal static string HidebysigToken {
            get {
                return ResourceManager.GetString("HidebysigToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        internal static string Identifier {
            get {
                return ResourceManager.GetString("Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImplementationAttributes.
        /// </summary>
        internal static string ImplementationAttributes {
            get {
                return ResourceManager.GetString("ImplementationAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImplementsClause.
        /// </summary>
        internal static string ImplementsClause {
            get {
                return ResourceManager.GetString("ImplementsClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InitToken.
        /// </summary>
        internal static string InitToken {
            get {
                return ResourceManager.GetString("InitToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InstanceToken.
        /// </summary>
        internal static string InstanceToken {
            get {
                return ResourceManager.GetString("InstanceToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruction.
        /// </summary>
        internal static string Instruction {
            get {
                return ResourceManager.GetString("Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InstructionBranch.
        /// </summary>
        internal static string InstructionBranch {
            get {
                return ResourceManager.GetString("InstructionBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InstructionInt.
        /// </summary>
        internal static string InstructionInt {
            get {
                return ResourceManager.GetString("InstructionInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InstructionMethod.
        /// </summary>
        internal static string InstructionMethod {
            get {
                return ResourceManager.GetString("InstructionMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InstructionNone.
        /// </summary>
        internal static string InstructionNone {
            get {
                return ResourceManager.GetString("InstructionNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InstructionString.
        /// </summary>
        internal static string InstructionString {
            get {
                return ResourceManager.GetString("InstructionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Int16Token.
        /// </summary>
        internal static string Int16Token {
            get {
                return ResourceManager.GetString("Int16Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Int32Token.
        /// </summary>
        internal static string Int32Token {
            get {
                return ResourceManager.GetString("Int32Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Int64Token.
        /// </summary>
        internal static string Int64Token {
            get {
                return ResourceManager.GetString("Int64Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Int8Token.
        /// </summary>
        internal static string Int8Token {
            get {
                return ResourceManager.GetString("Int8Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer.
        /// </summary>
        internal static string Integer {
            get {
                return ResourceManager.GetString("Integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ldarg0Token.
        /// </summary>
        internal static string Ldarg0Token {
            get {
                return ResourceManager.GetString("Ldarg0Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ldci40Token.
        /// </summary>
        internal static string Ldci40Token {
            get {
                return ResourceManager.GetString("Ldci40Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ldci41Token.
        /// </summary>
        internal static string Ldci41Token {
            get {
                return ResourceManager.GetString("Ldci41Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ldci42Token.
        /// </summary>
        internal static string Ldci42Token {
            get {
                return ResourceManager.GetString("Ldci42Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ldci43Token.
        /// </summary>
        internal static string Ldci43Token {
            get {
                return ResourceManager.GetString("Ldci43Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ldci44Token.
        /// </summary>
        internal static string Ldci44Token {
            get {
                return ResourceManager.GetString("Ldci44Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ldci45Token.
        /// </summary>
        internal static string Ldci45Token {
            get {
                return ResourceManager.GetString("Ldci45Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ldci46Token.
        /// </summary>
        internal static string Ldci46Token {
            get {
                return ResourceManager.GetString("Ldci46Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ldci47Token.
        /// </summary>
        internal static string Ldci47Token {
            get {
                return ResourceManager.GetString("Ldci47Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ldci48Token.
        /// </summary>
        internal static string Ldci48Token {
            get {
                return ResourceManager.GetString("Ldci48Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ldci4m1AliasToken.
        /// </summary>
        internal static string Ldci4m1AliasToken {
            get {
                return ResourceManager.GetString("Ldci4m1AliasToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ldci4m1Token.
        /// </summary>
        internal static string Ldci4m1Token {
            get {
                return ResourceManager.GetString("Ldci4m1Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ldci4sToken.
        /// </summary>
        internal static string Ldci4sToken {
            get {
                return ResourceManager.GetString("Ldci4sToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ldci4Token.
        /// </summary>
        internal static string Ldci4Token {
            get {
                return ResourceManager.GetString("Ldci4Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ldloc0Token.
        /// </summary>
        internal static string Ldloc0Token {
            get {
                return ResourceManager.GetString("Ldloc0Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ldloc1Token.
        /// </summary>
        internal static string Ldloc1Token {
            get {
                return ResourceManager.GetString("Ldloc1Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ldloc2Token.
        /// </summary>
        internal static string Ldloc2Token {
            get {
                return ResourceManager.GetString("Ldloc2Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ldloc3Token.
        /// </summary>
        internal static string Ldloc3Token {
            get {
                return ResourceManager.GetString("Ldloc3Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LdstrToken.
        /// </summary>
        internal static string LdstrToken {
            get {
                return ResourceManager.GetString("LdstrToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeavesToken.
        /// </summary>
        internal static string LeavesToken {
            get {
                return ResourceManager.GetString("LeavesToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeaveToken.
        /// </summary>
        internal static string LeaveToken {
            get {
                return ResourceManager.GetString("LeaveToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftBrace.
        /// </summary>
        internal static string LeftBrace {
            get {
                return ResourceManager.GetString("LeftBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftParenthesis.
        /// </summary>
        internal static string LeftParenthesis {
            get {
                return ResourceManager.GetString("LeftParenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftSquareBracket.
        /// </summary>
        internal static string LeftSquareBracket {
            get {
                return ResourceManager.GetString("LeftSquareBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LineComment.
        /// </summary>
        internal static string LineComment {
            get {
                return ResourceManager.GetString("LineComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocalsHead.
        /// </summary>
        internal static string LocalsHead {
            get {
                return ResourceManager.GetString("LocalsHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LongInteger.
        /// </summary>
        internal static string LongInteger {
            get {
                return ResourceManager.GetString("LongInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ManagedToken.
        /// </summary>
        internal static string ManagedToken {
            get {
                return ResourceManager.GetString("ManagedToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MethodAttributes.
        /// </summary>
        internal static string MethodAttributes {
            get {
                return ResourceManager.GetString("MethodAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MethodDeclaration.
        /// </summary>
        internal static string MethodDeclaration {
            get {
                return ResourceManager.GetString("MethodDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MethodDeclarations.
        /// </summary>
        internal static string MethodDeclarations {
            get {
                return ResourceManager.GetString("MethodDeclarations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MethodHead.
        /// </summary>
        internal static string MethodHead {
            get {
                return ResourceManager.GetString("MethodHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MethodName.
        /// </summary>
        internal static string MethodName {
            get {
                return ResourceManager.GetString("MethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModuleHead.
        /// </summary>
        internal static string ModuleHead {
            get {
                return ResourceManager.GetString("ModuleHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MulovfToken.
        /// </summary>
        internal static string MulovfToken {
            get {
                return ResourceManager.GetString("MulovfToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MulovfunToken.
        /// </summary>
        internal static string MulovfunToken {
            get {
                return ResourceManager.GetString("MulovfunToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MulToken.
        /// </summary>
        internal static string MulToken {
            get {
                return ResourceManager.GetString("MulToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NegToken.
        /// </summary>
        internal static string NegToken {
            get {
                return ResourceManager.GetString("NegToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NopToken.
        /// </summary>
        internal static string NopToken {
            get {
                return ResourceManager.GetString("NopToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotToken.
        /// </summary>
        internal static string NotToken {
            get {
                return ResourceManager.GetString("NotToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObjectToken.
        /// </summary>
        internal static string ObjectToken {
            get {
                return ResourceManager.GetString("ObjectToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrToken.
        /// </summary>
        internal static string OrToken {
            get {
                return ResourceManager.GetString("OrToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParamAttributes.
        /// </summary>
        internal static string ParamAttributes {
            get {
                return ResourceManager.GetString("ParamAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plus.
        /// </summary>
        internal static string Plus {
            get {
                return ResourceManager.GetString("Plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PopToken.
        /// </summary>
        internal static string PopToken {
            get {
                return ResourceManager.GetString("PopToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrivateToken.
        /// </summary>
        internal static string PrivateToken {
            get {
                return ResourceManager.GetString("PrivateToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PublicKeyTokenHead.
        /// </summary>
        internal static string PublicKeyTokenHead {
            get {
                return ResourceManager.GetString("PublicKeyTokenHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PublicToken.
        /// </summary>
        internal static string PublicToken {
            get {
                return ResourceManager.GetString("PublicToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuotedString.
        /// </summary>
        internal static string QuotedString {
            get {
                return ResourceManager.GetString("QuotedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemToken.
        /// </summary>
        internal static string RemToken {
            get {
                return ResourceManager.GetString("RemToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemunToken.
        /// </summary>
        internal static string RemunToken {
            get {
                return ResourceManager.GetString("RemunToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RetToken.
        /// </summary>
        internal static string RetToken {
            get {
                return ResourceManager.GetString("RetToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RightBrace.
        /// </summary>
        internal static string RightBrace {
            get {
                return ResourceManager.GetString("RightBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RightParenthesis.
        /// </summary>
        internal static string RightParenthesis {
            get {
                return ResourceManager.GetString("RightParenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RightSquareBracket.
        /// </summary>
        internal static string RightSquareBracket {
            get {
                return ResourceManager.GetString("RightSquareBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RtspecialnameToken.
        /// </summary>
        internal static string RtspecialnameToken {
            get {
                return ResourceManager.GetString("RtspecialnameToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShlToken.
        /// </summary>
        internal static string ShlToken {
            get {
                return ResourceManager.GetString("ShlToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShrToken.
        /// </summary>
        internal static string ShrToken {
            get {
                return ResourceManager.GetString("ShrToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignatureArgument.
        /// </summary>
        internal static string SignatureArgument {
            get {
                return ResourceManager.GetString("SignatureArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignatureArguments0.
        /// </summary>
        internal static string SignatureArguments0 {
            get {
                return ResourceManager.GetString("SignatureArguments0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignatureArguments1.
        /// </summary>
        internal static string SignatureArguments1 {
            get {
                return ResourceManager.GetString("SignatureArguments1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SlashedName.
        /// </summary>
        internal static string SlashedName {
            get {
                return ResourceManager.GetString("SlashedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpecialnameToken.
        /// </summary>
        internal static string SpecialnameToken {
            get {
                return ResourceManager.GetString("SpecialnameToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StaticToken.
        /// </summary>
        internal static string StaticToken {
            get {
                return ResourceManager.GetString("StaticToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stloc0Token.
        /// </summary>
        internal static string Stloc0Token {
            get {
                return ResourceManager.GetString("Stloc0Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stloc1Token.
        /// </summary>
        internal static string Stloc1Token {
            get {
                return ResourceManager.GetString("Stloc1Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stloc2Token.
        /// </summary>
        internal static string Stloc2Token {
            get {
                return ResourceManager.GetString("Stloc2Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stloc3Token.
        /// </summary>
        internal static string Stloc3Token {
            get {
                return ResourceManager.GetString("Stloc3Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StringToken.
        /// </summary>
        internal static string StringToken {
            get {
                return ResourceManager.GetString("StringToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubovfToken.
        /// </summary>
        internal static string SubovfToken {
            get {
                return ResourceManager.GetString("SubovfToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubovfunToken.
        /// </summary>
        internal static string SubovfunToken {
            get {
                return ResourceManager.GetString("SubovfunToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubToken.
        /// </summary>
        internal static string SubToken {
            get {
                return ResourceManager.GetString("SubToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypeSpecification.
        /// </summary>
        internal static string TypeSpecification {
            get {
                return ResourceManager.GetString("TypeSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uint16Token.
        /// </summary>
        internal static string Uint16Token {
            get {
                return ResourceManager.GetString("Uint16Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uint32Token.
        /// </summary>
        internal static string Uint32Token {
            get {
                return ResourceManager.GetString("Uint32Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uint64Token.
        /// </summary>
        internal static string Uint64Token {
            get {
                return ResourceManager.GetString("Uint64Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uint8Token.
        /// </summary>
        internal static string Uint8Token {
            get {
                return ResourceManager.GetString("Uint8Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValuetypeToken.
        /// </summary>
        internal static string ValuetypeToken {
            get {
                return ResourceManager.GetString("ValuetypeToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VoidToken.
        /// </summary>
        internal static string VoidToken {
            get {
                return ResourceManager.GetString("VoidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XorToken.
        /// </summary>
        internal static string XorToken {
            get {
                return ResourceManager.GetString("XorToken", resourceCulture);
            }
        }
    }
}
