//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CILantro.Grammar {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GrammarNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GrammarNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CILantro.Grammar.GrammarNames", typeof(GrammarNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to asmOrRefDecl.
        /// </summary>
        public static string asmOrRefDecl {
            get {
                return ResourceManager.GetString("asmOrRefDecl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assemblyRefDecl.
        /// </summary>
        public static string assemblyRefDecl {
            get {
                return ResourceManager.GetString("assemblyRefDecl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assemblyRefDecls.
        /// </summary>
        public static string assemblyRefDecls {
            get {
                return ResourceManager.GetString("assemblyRefDecls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assemblyRefHead.
        /// </summary>
        public static string assemblyRefHead {
            get {
                return ResourceManager.GetString("assemblyRefHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bytes.
        /// </summary>
        public static string bytes {
            get {
                return ResourceManager.GetString("bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMMENTS_LINECOMMENT.
        /// </summary>
        public static string COMMENTS_LINECOMMENT {
            get {
                return ResourceManager.GetString("COMMENTS_LINECOMMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to decl.
        /// </summary>
        public static string decl {
            get {
                return ResourceManager.GetString("decl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to decls.
        /// </summary>
        public static string decls {
            get {
                return ResourceManager.GetString("decls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hexbytes.
        /// </summary>
        public static string hexbytes {
            get {
                return ResourceManager.GetString("hexbytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id.
        /// </summary>
        public static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to int32.
        /// </summary>
        public static string int32 {
            get {
                return ResourceManager.GetString("int32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEXICALS_HEXBYTE.
        /// </summary>
        public static string LEXICALS_HEXBYTE {
            get {
                return ResourceManager.GetString("LEXICALS_HEXBYTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEXICALS_ID.
        /// </summary>
        public static string LEXICALS_ID {
            get {
                return ResourceManager.GetString("LEXICALS_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEXICALS_INT32.
        /// </summary>
        public static string LEXICALS_INT32 {
            get {
                return ResourceManager.GetString("LEXICALS_INT32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name1.
        /// </summary>
        public static string name1 {
            get {
                return ResourceManager.GetString("name1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to publicKeyTokenHead.
        /// </summary>
        public static string publicKeyTokenHead {
            get {
                return ResourceManager.GetString("publicKeyTokenHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start.
        /// </summary>
        public static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
    }
}
