//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CILantro.Grammar {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GrammarNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GrammarNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CILantro.Grammar.GrammarNames", typeof(GrammarNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to asmAttr.
        /// </summary>
        public static string asmAttr {
            get {
                return ResourceManager.GetString("asmAttr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to asmOrRefDecl.
        /// </summary>
        public static string asmOrRefDecl {
            get {
                return ResourceManager.GetString("asmOrRefDecl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assemblyDecl.
        /// </summary>
        public static string assemblyDecl {
            get {
                return ResourceManager.GetString("assemblyDecl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assemblyDecls.
        /// </summary>
        public static string assemblyDecls {
            get {
                return ResourceManager.GetString("assemblyDecls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assemblyHead.
        /// </summary>
        public static string assemblyHead {
            get {
                return ResourceManager.GetString("assemblyHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assemblyRefDecl.
        /// </summary>
        public static string assemblyRefDecl {
            get {
                return ResourceManager.GetString("assemblyRefDecl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assemblyRefDecls.
        /// </summary>
        public static string assemblyRefDecls {
            get {
                return ResourceManager.GetString("assemblyRefDecls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assemblyRefHead.
        /// </summary>
        public static string assemblyRefHead {
            get {
                return ResourceManager.GetString("assemblyRefHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to atOpt.
        /// </summary>
        public static string atOpt {
            get {
                return ResourceManager.GetString("atOpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bytes.
        /// </summary>
        public static string bytes {
            get {
                return ResourceManager.GetString("bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to call.
        /// </summary>
        public static string call {
            get {
                return ResourceManager.GetString("call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to callConv.
        /// </summary>
        public static string callConv {
            get {
                return ResourceManager.GetString("callConv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to callKind.
        /// </summary>
        public static string callKind {
            get {
                return ResourceManager.GetString("callKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to classAttr.
        /// </summary>
        public static string classAttr {
            get {
                return ResourceManager.GetString("classAttr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to classDecl.
        /// </summary>
        public static string classDecl {
            get {
                return ResourceManager.GetString("classDecl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to classDecls.
        /// </summary>
        public static string classDecls {
            get {
                return ResourceManager.GetString("classDecls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to classHead.
        /// </summary>
        public static string classHead {
            get {
                return ResourceManager.GetString("classHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to className.
        /// </summary>
        public static string className {
            get {
                return ResourceManager.GetString("className", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMMENTS_LINECOMMENT.
        /// </summary>
        public static string COMMENTS_LINECOMMENT {
            get {
                return ResourceManager.GetString("COMMENTS_LINECOMMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to compQstring.
        /// </summary>
        public static string compQstring {
            get {
                return ResourceManager.GetString("compQstring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customAttrDecl.
        /// </summary>
        public static string customAttrDecl {
            get {
                return ResourceManager.GetString("customAttrDecl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customHead.
        /// </summary>
        public static string customHead {
            get {
                return ResourceManager.GetString("customHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customType.
        /// </summary>
        public static string customType {
            get {
                return ResourceManager.GetString("customType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to decl.
        /// </summary>
        public static string decl {
            get {
                return ResourceManager.GetString("decl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to decls.
        /// </summary>
        public static string decls {
            get {
                return ResourceManager.GetString("decls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .ctor.
        /// </summary>
        public static string dotCtor {
            get {
                return ResourceManager.GetString("dotCtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to extendsClause.
        /// </summary>
        public static string extendsClause {
            get {
                return ResourceManager.GetString("extendsClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fieldAttr.
        /// </summary>
        public static string fieldAttr {
            get {
                return ResourceManager.GetString("fieldAttr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fieldDecl.
        /// </summary>
        public static string fieldDecl {
            get {
                return ResourceManager.GetString("fieldDecl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to genericClassName.
        /// </summary>
        public static string genericClassName {
            get {
                return ResourceManager.GetString("genericClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to genericMethodName.
        /// </summary>
        public static string genericMethodName {
            get {
                return ResourceManager.GetString("genericMethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hexbytes.
        /// </summary>
        public static string hexbytes {
            get {
                return ResourceManager.GetString("hexbytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id.
        /// </summary>
        public static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to implAttr.
        /// </summary>
        public static string implAttr {
            get {
                return ResourceManager.GetString("implAttr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to implClause.
        /// </summary>
        public static string implClause {
            get {
                return ResourceManager.GetString("implClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to initOpt.
        /// </summary>
        public static string initOpt {
            get {
                return ResourceManager.GetString("initOpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to instr.
        /// </summary>
        public static string instr {
            get {
                return ResourceManager.GetString("instr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSTR_BRTARGET.
        /// </summary>
        public static string INSTR_BRTARGET {
            get {
                return ResourceManager.GetString("INSTR_BRTARGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSTR_FIELD.
        /// </summary>
        public static string INSTR_FIELD {
            get {
                return ResourceManager.GetString("INSTR_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSTR_I.
        /// </summary>
        public static string INSTR_I {
            get {
                return ResourceManager.GetString("INSTR_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSTR_METHOD.
        /// </summary>
        public static string INSTR_METHOD {
            get {
                return ResourceManager.GetString("INSTR_METHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSTR_NONE.
        /// </summary>
        public static string INSTR_NONE {
            get {
                return ResourceManager.GetString("INSTR_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSTR_STRING.
        /// </summary>
        public static string INSTR_STRING {
            get {
                return ResourceManager.GetString("INSTR_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSTR_TOK.
        /// </summary>
        public static string INSTR_TOK {
            get {
                return ResourceManager.GetString("INSTR_TOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to instr_tok_head.
        /// </summary>
        public static string instr_tok_head {
            get {
                return ResourceManager.GetString("instr_tok_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSTR_TYPE.
        /// </summary>
        public static string INSTR_TYPE {
            get {
                return ResourceManager.GetString("INSTR_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSTR_VAR.
        /// </summary>
        public static string INSTR_VAR {
            get {
                return ResourceManager.GetString("INSTR_VAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to node_int32.
        /// </summary>
        public static string int32 {
            get {
                return ResourceManager.GetString("int32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to node_int64.
        /// </summary>
        public static string int64 {
            get {
                return ResourceManager.GetString("int64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string keyword_add {
            get {
                return ResourceManager.GetString("keyword_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string keyword_and {
            get {
                return ResourceManager.GetString("keyword_and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ble.s.
        /// </summary>
        public static string keyword_bles {
            get {
                return ResourceManager.GetString("keyword_bles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bool.
        /// </summary>
        public static string keyword_bool {
            get {
                return ResourceManager.GetString("keyword_bool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ceq.
        /// </summary>
        public static string keyword_ceq {
            get {
                return ResourceManager.GetString("keyword_ceq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cgt.
        /// </summary>
        public static string keyword_cgt {
            get {
                return ResourceManager.GetString("keyword_cgt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to char.
        /// </summary>
        public static string keyword_char {
            get {
                return ResourceManager.GetString("keyword_char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clt.
        /// </summary>
        public static string keyword_clt {
            get {
                return ResourceManager.GetString("keyword_clt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.
        /// </summary>
        public static string keyword_div {
            get {
                return ResourceManager.GetString("keyword_div", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .entrypoint.
        /// </summary>
        public static string keyword_dotEntrypoint {
            get {
                return ResourceManager.GetString("keyword_dotEntrypoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .locals.
        /// </summary>
        public static string keyword_dotLocals {
            get {
                return ResourceManager.GetString("keyword_dotLocals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dup.
        /// </summary>
        public static string keyword_dup {
            get {
                return ResourceManager.GetString("keyword_dup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to float32.
        /// </summary>
        public static string keyword_float32 {
            get {
                return ResourceManager.GetString("keyword_float32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to float64.
        /// </summary>
        public static string keyword_float64 {
            get {
                return ResourceManager.GetString("keyword_float64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to init.
        /// </summary>
        public static string keyword_init {
            get {
                return ResourceManager.GetString("keyword_init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to instance.
        /// </summary>
        public static string keyword_instance {
            get {
                return ResourceManager.GetString("keyword_instance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to int16.
        /// </summary>
        public static string keyword_int16 {
            get {
                return ResourceManager.GetString("keyword_int16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to int32.
        /// </summary>
        public static string keyword_int32 {
            get {
                return ResourceManager.GetString("keyword_int32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to int64.
        /// </summary>
        public static string keyword_int64 {
            get {
                return ResourceManager.GetString("keyword_int64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to int8.
        /// </summary>
        public static string keyword_int8 {
            get {
                return ResourceManager.GetString("keyword_int8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ldarg.0.
        /// </summary>
        public static string keyword_ldarg0 {
            get {
                return ResourceManager.GetString("keyword_ldarg0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ldc.i4.0.
        /// </summary>
        public static string keyword_ldci40 {
            get {
                return ResourceManager.GetString("keyword_ldci40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ldc.i4.1.
        /// </summary>
        public static string keyword_ldci41 {
            get {
                return ResourceManager.GetString("keyword_ldci41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ldc.i4.s.
        /// </summary>
        public static string keyword_ldci4s {
            get {
                return ResourceManager.GetString("keyword_ldci4s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ldloc.0.
        /// </summary>
        public static string keyword_ldloc0 {
            get {
                return ResourceManager.GetString("keyword_ldloc0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ldloc.1.
        /// </summary>
        public static string keyword_ldloc1 {
            get {
                return ResourceManager.GetString("keyword_ldloc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ldloc.2.
        /// </summary>
        public static string keyword_ldloc2 {
            get {
                return ResourceManager.GetString("keyword_ldloc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ldloc.3.
        /// </summary>
        public static string keyword_ldloc3 {
            get {
                return ResourceManager.GetString("keyword_ldloc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ldloca.s.
        /// </summary>
        public static string keyword_ldlocas {
            get {
                return ResourceManager.GetString("keyword_ldlocas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ldloc.s.
        /// </summary>
        public static string keyword_ldlocs {
            get {
                return ResourceManager.GetString("keyword_ldlocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ldstr.
        /// </summary>
        public static string keyword_ldstr {
            get {
                return ResourceManager.GetString("keyword_ldstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mul.
        /// </summary>
        public static string keyword_mul {
            get {
                return ResourceManager.GetString("keyword_mul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not.
        /// </summary>
        public static string keyword_not {
            get {
                return ResourceManager.GetString("keyword_not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string keyword_or {
            get {
                return ResourceManager.GetString("keyword_or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pop.
        /// </summary>
        public static string keyword_pop {
            get {
                return ResourceManager.GetString("keyword_pop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rem.
        /// </summary>
        public static string keyword_rem {
            get {
                return ResourceManager.GetString("keyword_rem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ret.
        /// </summary>
        public static string keyword_ret {
            get {
                return ResourceManager.GetString("keyword_ret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shl.
        /// </summary>
        public static string keyword_shl {
            get {
                return ResourceManager.GetString("keyword_shl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shr.
        /// </summary>
        public static string keyword_shr {
            get {
                return ResourceManager.GetString("keyword_shr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stloc.0.
        /// </summary>
        public static string keyword_stloc0 {
            get {
                return ResourceManager.GetString("keyword_stloc0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stloc.1.
        /// </summary>
        public static string keyword_stloc1 {
            get {
                return ResourceManager.GetString("keyword_stloc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stloc.2.
        /// </summary>
        public static string keyword_stloc2 {
            get {
                return ResourceManager.GetString("keyword_stloc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stloc.3.
        /// </summary>
        public static string keyword_stloc3 {
            get {
                return ResourceManager.GetString("keyword_stloc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stloc.s.
        /// </summary>
        public static string keyword_stlocs {
            get {
                return ResourceManager.GetString("keyword_stlocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to string.
        /// </summary>
        public static string keyword_string {
            get {
                return ResourceManager.GetString("keyword_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sub.
        /// </summary>
        public static string keyword_sub {
            get {
                return ResourceManager.GetString("keyword_sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uint16.
        /// </summary>
        public static string keyword_uint16 {
            get {
                return ResourceManager.GetString("keyword_uint16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uint32.
        /// </summary>
        public static string keyword_uint32 {
            get {
                return ResourceManager.GetString("keyword_uint32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uint64.
        /// </summary>
        public static string keyword_uint64 {
            get {
                return ResourceManager.GetString("keyword_uint64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uint8.
        /// </summary>
        public static string keyword_uint8 {
            get {
                return ResourceManager.GetString("keyword_uint8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to valuetype.
        /// </summary>
        public static string keyword_valuetype {
            get {
                return ResourceManager.GetString("keyword_valuetype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to void.
        /// </summary>
        public static string keyword_void {
            get {
                return ResourceManager.GetString("keyword_void", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xor.
        /// </summary>
        public static string keyword_xor {
            get {
                return ResourceManager.GetString("keyword_xor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEXICALS_HEXBYTE.
        /// </summary>
        public static string LEXICALS_HEXBYTE {
            get {
                return ResourceManager.GetString("LEXICALS_HEXBYTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEXICALS_ID.
        /// </summary>
        public static string LEXICALS_ID {
            get {
                return ResourceManager.GetString("LEXICALS_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEXICALS_INT32.
        /// </summary>
        public static string LEXICALS_INT32 {
            get {
                return ResourceManager.GetString("LEXICALS_INT32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEXICALS_INT32_DEC.
        /// </summary>
        public static string LEXICALS_INT32_DEC {
            get {
                return ResourceManager.GetString("LEXICALS_INT32_DEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEXICALS_INT32_HEX.
        /// </summary>
        public static string LEXICALS_INT32_HEX {
            get {
                return ResourceManager.GetString("LEXICALS_INT32_HEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEXICALS_INT64.
        /// </summary>
        public static string LEXICALS_INT64 {
            get {
                return ResourceManager.GetString("LEXICALS_INT64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEXICALS_INT64_DEC.
        /// </summary>
        public static string LEXICALS_INT64_DEC {
            get {
                return ResourceManager.GetString("LEXICALS_INT64_DEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEXICALS_INT64_HEX.
        /// </summary>
        public static string LEXICALS_INT64_HEX {
            get {
                return ResourceManager.GetString("LEXICALS_INT64_HEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEXICALS_QSTRING.
        /// </summary>
        public static string LEXICALS_QSTRING {
            get {
                return ResourceManager.GetString("LEXICALS_QSTRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEXICALS_SQSTRING.
        /// </summary>
        public static string LEXICALS_SQSTRING {
            get {
                return ResourceManager.GetString("LEXICALS_SQSTRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to localsHead.
        /// </summary>
        public static string localsHead {
            get {
                return ResourceManager.GetString("localsHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manifestResDecl.
        /// </summary>
        public static string manifestResDecl {
            get {
                return ResourceManager.GetString("manifestResDecl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manifestResDecls.
        /// </summary>
        public static string manifestResDecls {
            get {
                return ResourceManager.GetString("manifestResDecls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manifestResHead.
        /// </summary>
        public static string manifestResHead {
            get {
                return ResourceManager.GetString("manifestResHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manresAttr.
        /// </summary>
        public static string manresAttr {
            get {
                return ResourceManager.GetString("manresAttr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to memberRef.
        /// </summary>
        public static string memberRef {
            get {
                return ResourceManager.GetString("memberRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to methAttr.
        /// </summary>
        public static string methAttr {
            get {
                return ResourceManager.GetString("methAttr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to methodDecl.
        /// </summary>
        public static string methodDecl {
            get {
                return ResourceManager.GetString("methodDecl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to methodDecls.
        /// </summary>
        public static string methodDecls {
            get {
                return ResourceManager.GetString("methodDecls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to methodHead.
        /// </summary>
        public static string methodHead {
            get {
                return ResourceManager.GetString("methodHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to methodHeadPart1.
        /// </summary>
        public static string methodHeadPart1 {
            get {
                return ResourceManager.GetString("methodHeadPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to methodName.
        /// </summary>
        public static string methodName {
            get {
                return ResourceManager.GetString("methodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moduleHead.
        /// </summary>
        public static string moduleHead {
            get {
                return ResourceManager.GetString("moduleHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name1.
        /// </summary>
        public static string name1 {
            get {
                return ResourceManager.GetString("name1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ownerType.
        /// </summary>
        public static string ownerType {
            get {
                return ResourceManager.GetString("ownerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paramAttr.
        /// </summary>
        public static string paramAttr {
            get {
                return ResourceManager.GetString("paramAttr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to propAttr.
        /// </summary>
        public static string propAttr {
            get {
                return ResourceManager.GetString("propAttr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to propDecl.
        /// </summary>
        public static string propDecl {
            get {
                return ResourceManager.GetString("propDecl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to propDecls.
        /// </summary>
        public static string propDecls {
            get {
                return ResourceManager.GetString("propDecls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to propHead.
        /// </summary>
        public static string propHead {
            get {
                return ResourceManager.GetString("propHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to publicKeyTokenHead.
        /// </summary>
        public static string publicKeyTokenHead {
            get {
                return ResourceManager.GetString("publicKeyTokenHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to repeatOpt.
        /// </summary>
        public static string repeatOpt {
            get {
                return ResourceManager.GetString("repeatOpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sigArg.
        /// </summary>
        public static string sigArg {
            get {
                return ResourceManager.GetString("sigArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sigArgs0.
        /// </summary>
        public static string sigArgs0 {
            get {
                return ResourceManager.GetString("sigArgs0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sigArgs1.
        /// </summary>
        public static string sigArgs1 {
            get {
                return ResourceManager.GetString("sigArgs1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to slashedName.
        /// </summary>
        public static string slashedName {
            get {
                return ResourceManager.GetString("slashedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start.
        /// </summary>
        public static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type.
        /// </summary>
        public static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to typeSpec.
        /// </summary>
        public static string typeSpec {
            get {
                return ResourceManager.GetString("typeSpec", resourceCulture);
            }
        }
    }
}
